### PR TITLE
CASMTRIAGE-3371 Add workaround to dns_records.py to allow for hostnames with _

### PR DESCRIPTION
**Pull request by mitchty**
Note workaround imports idna at the top so that requests/urllib3 implicit
imports later work as expected.

## Summary and Scope

Adding _ as allowed character for idna library used by requests/urllib3.

Change could be ported anywhere, but realistically should only be used where we have _'s in at least ssl SAN names. For 1.3 we should remove the _'s entirely which is why this is only targeted to 1.2.

## Issues and Related PRs

* Resolves CASMTRIAGE-3371

## Testing

Validated on Hela m001/2 where 1 exhibited the behavior with an updated library, and 2 did not. Changes allowed 1 to no longer reject our short names with _'s in them.

### Tested on:

  * Hela

### Test description:

Copied script to hela on a failing and working node to validate behavior is the same.

- Were the install/upgrade-based validation checks/tests run (goss tests/install-validation doc)? n/a
- Were continuous integration tests run? If not, why? n/a
- Was upgrade tested? If not, why? n/a
- Was downgrade tested? If not, why? n/a
- Were new tests (or test issues/Jiras) created for this change? no

## Risks and Mitigations

Realistically we should remove the _ domain names to not need this change.

## Pull Request Checklist

- [ ] Version number(s) incremented, if applicable
- [ ] Copyrights updated
- [ ] License file intact
- [ ] Target branch correct
- [ ] CHANGELOG.md updated
- [ ] Testing is appropriate and complete, if applicable
- [ ] [HPC Product Announcement](https://cray.slack.com/archives/C026TVCSXLH) prepared, if applicable

### CODE REVIEW

**Review by spillerc-hpe — APPROVED** [review]

**Comment by spillerc-hpe** [comment]
Needs .version bump and changelog.md update at which point we can merge and update csm-rpms.

**Comment by mitchty** [comment]
Will do let me update the branch with that in a separate commit.

**Comment by mitchty** [comment]
Quick question, should I open a new pr to master for this too? I was under the impression this would only be a temporary fix for 1.2 and we don't want it for 1.3 but if we have a version bump then things get a slosh more complect.

**Comment by rustydb** [comment]
@mitchty you just need to resolve the changelog conflict, presumably this PR can go into 0.0.38 _with_ #15 .

**Comment by mitchty** [comment]
So I'm not seeing any changelog conflict for this branch I'll open a different pr for main.

**Review by rustydb — APPROVED** [review]

**Pull request merged**
